version: '3.4'

services:

  arbeitzeitdb:
    container_name: arbeitzeitdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=ArbeitzeitDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin123
    restart: always
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin

  identityservice.api:
    container_name: identityservice.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=arbeitzeitdb;Port=5432;Database=ArbeitzeitDb;User Id=admin;Password=admin1234"
    depends_on:
      - arbeitzeitdb
    ports:
      - "8000:80"

  attendance.api:
    container_name: attendance.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=arbeitzeitdb;Port=5432;Database=ArbeitzeitDb;User Id=admin;Password=admin1234"
    depends_on:
      - arbeitzeitdb
    ports:
      - "8001:80"

  ocelotapigateway.mobile:
    container_name: apigateway.mobile
    depends_on:
      - attendance.api
      - identityservice.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8010:80"

